### ISSUE TITLE
all option buttons fulltext in title screen

### ISSUE THREAD

**Issue by minotalen** [pedropsi/game-bar-source#23]
**Why**
Players new to the game bar might not know the function of each button. It might be nice if the game bar would diplay the function in text while the game is in main menu before switching to the icons.
This has accessibility benefits. It will also make it much easier to introduce new icons in the future.

**What**
While in main menu, display the game bar like 
| hints | undo | restart | level select | music | fullscreen |

**How**
need a function to determine if in main menu, also bar item width needs to be constant which might be difficult.

**Comment by minotalen** [comment]
or maybe even
| **h**ints | **u**ndo | **r**estart | **l**evel select | **m**usic | **f**ullscreen |

**Comment by pedropsi** [comment]
Superseded by the typewriter effect
