### ISSUE TITLE
game recommendations

### ISSUE THREAD

**Issue by minotalen** [pedropsi/game-bar-source#25]
**Why**
after the player is finished playing your game, they are likely to just close the tab and move on with their life. since we want to prevent this and eternally keep them in the grips of our webpage we need to provide them with an alternate option. when embedding games on external sites it would be nice to have a feature that draws some traffic in.

**What**
after the player has finished a game and registered for the hall of fame, show them 3 other games. these could be either hand-picked (for game series like BK and SB...) or picked from a list. List always shows most recent game and 2 random games.

**Comment by pedropsi** [comment]
While the recommendations could be a good idea, I strongly disagree with 
"eternally keep them in the grips of our webpage". Being a black hole is not our goal. People are free to leave and come back anytime, and the time they spend here should ideally be both memorable and as short as possible, to complement a balanced, healthy life.
