### ISSUE TITLE
bookmarklet not working on itch anymore

### ISSUE THREAD

**Issue by minotalen** [pedropsi/game-bar-source#32]
**Describe the bug**
the bookmarklet does not seem to work on itch.io games anymore.

**To Reproduce**
1. Go to https://w.itch.io/herding-cats
2. Click on game bar bookmarklet
3. ???
4. see that nothing happens

**Expected behavior**
game bar opening

**Comment by pedropsi** [comment]
It is impossible (due to same origin policy) to load the bar inside the iframe in itchio and similar sites. Should add this to the site docs!
