### ISSUE TITLE
Level Categories

### ISSUE THREAD

**Issue by minotalen** [pedropsi/game-bar-source#4]
**Why**
It would be nice to have a way of defining level categories, so that levels can be grouped by mechanic/complexity.

**What**
Levels are divided into categories in the level select menu. 
Each category is shown as **'Category name   00/XX'** where XX is the amount of levels in that category and 00 is the amount of solved levels in that category.
Ideally categories can be collapsed and expanded.

**How**
One array gives the category titles, another array the # of levels for each of the categories.
catName = [Intro, Beginner, Advanced, Expert]
catAmt = [4, 7, 11, 9]

**Comment by pedropsi** [comment]
Added to the hints file, via the § symbol.
See platformer template for how it looks like.
